name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false