name: Build

on: [push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: false